Repository Gam-develop/gam-server, pull requests merged in 2023-07, with the labels that each got.

#7 feat/#3: user Scrap api 개발
  src/main/java/com/gam/api/common/ErrorHandler.java
  src/main/java/com/gam/api/common/ExceptionMessage.java
  src/main/java/com/gam/api/common/exception/GamException.java
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/config/SecurityConfig.java
  src/main/java/com/gam/api/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gam/api/config/jwt/JwtTokenManager.java
  src/main/java/com/gam/api/controller/SocialController.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/UserInfoEditRequestDto.java
  src/main/java/com/gam/api/dto/user/UserScrapRequestDto.java
  src/main/java/com/gam/api/dto/user/UserScrapResponseDto.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/entity/UserScrap.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/repository/UserScrapRepository.java
  src/main/java/com/gam/api/service/UserService.java
  src/main/java/com/gam/api/service/UserServiceImpl.java
Labels: feat

#9 feat/#6: Presigned url s3
  .DS_Store
  build.gradle
  src/.DS_Store
  src/main/.DS_Store
  src/main/java/com/gam/api/common/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/config/S3Config.java
  src/main/java/com/gam/api/controller/S3Controller.java
  src/main/java/com/gam/api/dto/image/PresignedRequestDTO.java
  src/main/java/com/gam/api/dto/image/PresignedResponseDTO.java
  src/main/java/com/gam/api/service/S3Service.java
Labels: size/M, feat

#11 코드 정리, 에러 핸들링
  src/main/java/com/gam/api/common/ErrorHandler.java
  src/main/java/com/gam/api/common/ExceptionMessage.java
  src/main/java/com/gam/api/common/exception/AuthException.java
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/config/SecurityConfig.java
  src/main/java/com/gam/api/config/WebMvcConfig.java
  src/main/java/com/gam/api/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gam/api/config/jwt/JwtExceptionFilter.java
  src/main/java/com/gam/api/config/jwt/JwtTokenManager.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/entity/UserScrap.java
  src/main/java/com/gam/api/repository/UserScrapRepository.java
  src/main/java/com/gam/api/service/S3Service.java
  src/main/java/com/gam/api/service/UserServiceImpl.java
Labels: size/S, chore

#14 feat: update user ExternalLink #13
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/UserInfoEditRequestDto.java
  src/main/java/com/gam/api/dto/user/request/UserExternalLinkRequestDto.java
  src/main/java/com/gam/api/dto/user/request/UserScrapRequestDto.java
  src/main/java/com/gam/api/dto/user/response/UserExternalLinkResponseDto.java
  src/main/java/com/gam/api/dto/user/response/UserScrapResponseDto.java
  src/main/java/com/gam/api/entity/Work.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/service/UserService.java
  src/main/java/com/gam/api/service/UserServiceImpl.java
Labels: size/XS, gahee, feat

#17 [ WORK 🛠] 프로필 가져오기
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/response/UserMyProfileResponse.java
  src/main/java/com/gam/api/service/UserService.java
  src/main/java/com/gam/api/service/UserServiceImpl.java
Labels: size/XL, size/M, gahee, feat

#18 [WORK 🛠] 작업물 생성, 삭제
  src/main/java/com/gam/api/common/exception/AwsException.java
  src/main/java/com/gam/api/common/exception/WorkException.java
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/common/util/AuthCommon.java
  src/main/java/com/gam/api/controller/S3Controller.java
  src/main/java/com/gam/api/controller/SocialController.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/controller/WorkController.java
  src/main/java/com/gam/api/dto/s3/request/ImageDeleteRequestDTO.java
  src/main/java/com/gam/api/dto/s3/request/PresignedRequestDTO.java
  src/main/java/com/gam/api/dto/s3/response/PresignedResponseDTO.java
  src/main/java/com/gam/api/dto/work/request/WorkCreateRequestDTO.java
  src/main/java/com/gam/api/dto/work/request/WorkDeleteRequestDTO.java
  src/main/java/com/gam/api/dto/work/response/WorkResponseDTO.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/entity/Work.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/repository/WorkRepository.java
  src/main/java/com/gam/api/service/AuthService.java
  src/main/java/com/gam/api/service/AuthServiceImpl.java
  src/main/java/com/gam/api/service/s3/S3Service.java
  src/main/java/com/gam/api/service/s3/S3ServiceImpl.java
  src/main/java/com/gam/api/service/social/KakaoSocialService.java
  src/main/java/com/gam/api/service/social/SocialService.java
  src/main/java/com/gam/api/service/social/SocialServiceProvider.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
  src/main/java/com/gam/api/service/work/WorkService.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/M, yongtaek, feat

#19 [WORK 🛠] 유저 - 자기소개 글 수정
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/request/UserProfileUpdateRequestDto.java
  src/main/java/com/gam/api/dto/user/response/UserProfileUpdateResponseDto.java
  src/main/java/com/gam/api/entity/Tag.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/entity/UserTag.java
  src/main/java/com/gam/api/repository/TagRepository.java
  src/main/java/com/gam/api/repository/UserTagRepository.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/XL, gahee, feat

#21 [CHORE 🛠] Base Entity추가
  src/main/java/com/gam/api/entity/AuthProvider.java
  src/main/java/com/gam/api/entity/Magazine.java
  src/main/java/com/gam/api/entity/MagazinePhoto.java
  src/main/java/com/gam/api/entity/MagazineScrap.java
  src/main/java/com/gam/api/entity/Question.java
  src/main/java/com/gam/api/entity/Report.java
  src/main/java/com/gam/api/entity/Tag.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/entity/UserScrap.java
  src/main/java/com/gam/api/entity/UserTag.java
  src/main/java/com/gam/api/entity/Work.java
  src/main/java/com/gam/api/entity/superclass/TimeStamped.java
Labels: size/XS, gahee, chore

#24 [WORK 🛠] 유저 - 대표작업물로 설정
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/WorkController.java
  src/main/java/com/gam/api/dto/work/request/WorkFirstAssignRequestDto.java
  src/main/java/com/gam/api/entity/Work.java
  src/main/java/com/gam/api/repository/WorkRepository.java
  src/main/java/com/gam/api/service/work/WorkService.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/M, gahee, feat

#26 [WORK 🛠] 유저 - 작업물 수정
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/request/UserWorkEditRequestDTO.java
  src/main/java/com/gam/api/dto/user/response/UserWorkEditResponseDTO.java
  src/main/java/com/gam/api/dto/work/request/WorkCreateRequestDTO.java
  src/main/java/com/gam/api/entity/Work.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/M, gahee, feat

#27 [USER 🛠] 유저 - 온보딩, 닉네임 중복체크
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gam/api/controller/SocialController.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/s3/response/PresignedResponseDTO.java
  src/main/java/com/gam/api/dto/social/request/SocialLoginRequestDTO.java
  src/main/java/com/gam/api/dto/social/response/SocialLoginResponseDTO.java
  src/main/java/com/gam/api/dto/user/request/UserOnboardRequestDTO.java
  src/main/java/com/gam/api/dto/user/response/UserExternalLinkResponseDto.java
  src/main/java/com/gam/api/dto/user/response/UserNameCheckResponseDTO.java
  src/main/java/com/gam/api/dto/user/response/UserProfileUpdateResponseDto.java
  src/main/java/com/gam/api/dto/user/response/UserScrapResponseDto.java
  src/main/java/com/gam/api/dto/work/response/WorkResponseDTO.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/service/social/KakaoSocialService.java
  src/main/java/com/gam/api/service/social/SocialService.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/M, yongtaek, feat

#30 [WORK 🛠] 스크랩한 유저들 보기
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/response/UserExternalLinkResponseDTO.java
  src/main/java/com/gam/api/dto/user/response/UserMyProfileResponseDTO.java
  src/main/java/com/gam/api/dto/user/response/UserProfileUpdateResponseDTO.java
  src/main/java/com/gam/api/dto/user/response/UserScrapResponseDTO.java
  src/main/java/com/gam/api/dto/user/response/UserScrapsResponseDTO.java
  src/main/java/com/gam/api/repository/UserScrapRepository.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/L, gahee, fix

#35 [WORK 🛠] 발견 - 유저 프로필보기
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/response/UserProfileResponseDTO.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/M, gahee, fix

#36 [WORK 🛠] 메인 - 감잡은 디자이너
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/response/UserResponseDTO.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/M, gahee, feat

#37 [WORK 🛠] 마이페이지 - 포트폴리오 리스트
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/work/response/WorkPortfolioGetResponseDTO.java
  src/main/java/com/gam/api/dto/work/response/WorkPortfolioListResponseDTO.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/repository/WorkRepository.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/L, yongtaek, feat

#39 [MAGAZINE 🛠] 매거진 기능
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/MagazineController.java
  src/main/java/com/gam/api/dto/magazine/request/MagazineScrapRequestDTO.java
  src/main/java/com/gam/api/dto/magazine/response/MagazineDetailResponseDTO.java
  src/main/java/com/gam/api/dto/magazine/response/MagazineResponseDTO.java
  src/main/java/com/gam/api/dto/magazine/response/MagazineScrapResponseDTO.java
  src/main/java/com/gam/api/dto/magazine/response/MagazineScrapsResponseDTO.java
  src/main/java/com/gam/api/entity/Magazine.java
  src/main/java/com/gam/api/entity/MagazineScrap.java
  src/main/java/com/gam/api/entity/Question.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/entity/UserScrap.java
  src/main/java/com/gam/api/repository/MagazineRepository.java
  src/main/java/com/gam/api/repository/MagazineScrapRepository.java
  src/main/java/com/gam/api/service/magazine/MagazineService.java
  src/main/java/com/gam/api/service/magazine/MagazineServiceImpl.java
Labels: size/L, yongtaek, feat

#41 [USER 🛠] 유저 - 유저 스크랩 로직 수정
  src/main/java/com/gam/api/repository/UserScrapRepository.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/M, gahee, feat

#45 [CHORE🛠] 유저 엔티티 변경
  src/main/java/com/gam/api/entity/User.java
Labels: size/S, gahee, chore

#46 [CHORE🛠] 메인 - 감잡은 디자이너 - 기획 후 반영
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/XS, fix, chore

#47 [ AUTH 🛠] 권한 반영, security refactor
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/util/AuthCommon.java
  src/main/java/com/gam/api/config/SecurityConfig.java
  src/main/java/com/gam/api/config/jwt/AdminAuthentication.java
  src/main/java/com/gam/api/config/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/gam/api/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gam/api/config/jwt/JwtTokenManager.java
  src/main/java/com/gam/api/controller/MagazineController.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/controller/WorkController.java
  src/main/java/com/gam/api/entity/GamUserDetails.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/entity/UserStatus.java
  src/main/java/com/gam/api/repository/AuthProviderRepository.java
  src/main/java/com/gam/api/service/social/KakaoSocialService.java
  src/main/java/com/gam/api/service/user/UserDetailsServiceImpl.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/L, yongtaek, feat, refactor

#51 [USER🛠] 비헨스, 인스타, 노션 링크 추가
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/request/UserExternalLinkRequestDto.java
  src/main/java/com/gam/api/dto/user/request/UserProfileUpdateRequestDTO.java
  src/main/java/com/gam/api/dto/user/request/UserScrapRequestDTO.java
  src/main/java/com/gam/api/dto/user/request/UserUpdateLinkRequestDTO.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/L, gahee, feat

#53 [FIX🛠] 코드 수정
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/work/response/WorkPortfolioListResponseDTO.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/S

#48 [WORK 🛠] 유저들의 정보 갖고 오기
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/response/UserDiscoveryResponseDTO.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/entity/Work.java
  src/main/java/com/gam/api/entity/superclass/TimeStamped.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/L, gahee, feat

#55 [FIX🛠] 머지 관련 오류 해결
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
Labels: size/XS

#57 [FEAT🛠] CI 테스트 #56
  src/main/java/com/gam/api/controller/TestController.java
Labels: size/XS

#58 [WORK 🛠] 매거진 검색
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/MagazineController.java
  src/main/java/com/gam/api/dto/magazine/response/MagazineSearchResponseDTO.java
  src/main/java/com/gam/api/repository/MagazineRepository.java
  src/main/java/com/gam/api/service/magazine/MagazineService.java
  src/main/java/com/gam/api/service/magazine/MagazineServiceImpl.java
Labels: size/M, gahee, feat

#62 [WORK🛠] 배포 테스트
  src/main/java/com/gam/api/controller/TestController.java
Labels: size/XS

#63 [WORK🛠] 배포 테스트
  src/main/java/com/gam/api/controller/TestController.java
Labels: size/XS

#60 [WORK🛠] 둘러보기 - 검색 API개발
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/search/response/SearchUserWorkDTO.java
  src/main/java/com/gam/api/repository/MagazineRepository.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/repository/WorkRepository.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/M, gahee, feat

#65 set1, set2 설정 완료 #64
  src/main/java/com/gam/api/controller/TestController.java
  src/main/resources/application.yml
Labels: size/S

#66 fix: edit .yml #64
  src/main/resources/application.yml
Labels: size/XS

#68 [WORK🛠] 검색 API 소문자 검색 추가
  src/main/java/com/gam/api/dto/search/response/SearchUserWorkDTO.java
  src/main/java/com/gam/api/repository/MagazineRepository.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/repository/UserTagRepository.java
  src/main/java/com/gam/api/repository/WorkRepository.java
  src/main/java/com/gam/api/service/magazine/MagazineServiceImpl.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/S, gahee, chore
