Repository Gam-develop/gam-server, pull requests merged in 2023-08, with the labels that each got.

#71 각종 url, 앱 버전 return
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/config/GamConfig.java
  src/main/java/com/gam/api/config/jwt/JwtAuthenticationFilter.java
  src/main/java/com/gam/api/controller/UrlController.java
  src/main/java/com/gam/api/dto/social/response/SocialLoginResponseDTO.java
  src/main/java/com/gam/api/dto/url/response/UrlResponseDTO.java
  src/main/java/com/gam/api/repository/MagazineRepository.java
  src/main/java/com/gam/api/service/magazine/MagazineServiceImpl.java
  src/main/java/com/gam/api/service/social/KakaoSocialService.java
Labels: size/M, yongtaek, feat

#73 nginx 적용
  scripts/deploy.sh
  scripts/switch.sh
Labels: size/M

#74 [WORK🛠] 리프레시, 로그아웃 with redis
  build.gradle
  src/main/java/com/gam/api/common/ErrorHandler.java
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/common/util/RedisUtil.java
  src/main/java/com/gam/api/config/RedisConfig.java
  src/main/java/com/gam/api/config/jwt/JwtTokenManager.java
  src/main/java/com/gam/api/controller/SocialController.java
  src/main/java/com/gam/api/dto/social/request/SocialLogoutRequestDTO.java
  src/main/java/com/gam/api/dto/social/request/SocialRefreshRequestDTO.java
  src/main/java/com/gam/api/dto/social/response/SocialLoginResponseDTO.java
  src/main/java/com/gam/api/dto/social/response/SocialRefreshResponseDTO.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/service/social/KakaoSocialService.java
  src/main/java/com/gam/api/service/social/SocialCommonService.java
  src/main/java/com/gam/api/service/social/SocialCommonServiceImpl.java
  src/main/java/com/gam/api/service/social/SocialService.java
Labels: size/L, yongtaek, feat, fix

#76 [WORK🛠] 마지막 포폴 시 링크 다 날리기
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/XS, yongtaek, feat

#79 Feat/#78 magazine api
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/config/SecurityConfig.java
  src/main/java/com/gam/api/config/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/gam/api/controller/AdminController.java
  src/main/java/com/gam/api/controller/MagazineController.java
  src/main/java/com/gam/api/dto/admin/magazine/request/MagazineCreateRequestDTO.java
  src/main/java/com/gam/api/dto/admin/magazine/response/MagazineCreateRequestDTO.java
  src/main/java/com/gam/api/dto/manager/magazine/response/MagazineListResponseDTO.java
  src/main/java/com/gam/api/repository/MagazineRepository.java
  src/main/java/com/gam/api/service/admin/AdminService.java
  src/main/java/com/gam/api/service/admin/AdminServiceImpl.java
  src/main/java/com/gam/api/service/user/UserDetailsServiceImpl.java
Labels: size/L, feat

#81 [FIX] manager -> admin route
  src/main/java/com/gam/api/config/jwt/CustomAccessDeniedHandler.java
  src/main/java/com/gam/api/controller/AdminController.java
  src/main/java/com/gam/api/dto/admin/magazine/response/MagazineListResponseDTO.java
  src/main/java/com/gam/api/service/admin/AdminService.java
  src/main/java/com/gam/api/service/admin/AdminServiceImpl.java
Labels: size/S

#87 [FIX🛠] kakao 로그인 방식 변경
  src/main/java/com/gam/api/dto/kakao/KakaoAccessTokenResponse.java
  src/main/java/com/gam/api/dto/social/request/SocialLoginRequestDTO.java
  src/main/java/com/gam/api/external/kakao/KakaoAuthApiClient.java
  src/main/java/com/gam/api/service/social/KakaoSocialService.java
Labels: size/M, yongtaek, fix

#84 [WORK🛠] 메거진 생성, 수정 api개발
  build.gradle
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/AdminController.java
  src/main/java/com/gam/api/dto/admin/magazine/request/MagazineCreateRequestDTO.java
  src/main/java/com/gam/api/dto/admin/magazine/request/MagazineRequestDTO.java
  src/main/java/com/gam/api/dto/admin/magazine/response/MagazineCreateRequestDTO.java
  src/main/java/com/gam/api/dto/magazine/response/MagazineDetailResponseDTO.java
  src/main/java/com/gam/api/entity/Magazine.java
  src/main/java/com/gam/api/entity/MagazinePhoto.java
  src/main/java/com/gam/api/entity/Question.java
  src/main/java/com/gam/api/repository/QuestionRepository.java
  src/main/java/com/gam/api/service/admin/AdminService.java
  src/main/java/com/gam/api/service/admin/AdminServiceImpl.java
Labels: size/L, gahee, feat
