Repository Gam-develop/gam-server, pull requests merged in 2024-02, with the labels that each got.

#135 fix:magazineUrl 모든 magazine response에 추가, scrapresponse 제외
  src/main/java/com/gam/api/dto/magazine/response/MagazineDetailResponseDTO.java
  src/main/java/com/gam/api/dto/magazine/response/MagazineResponseDTO.java
  src/main/java/com/gam/api/dto/magazine/response/MagazineScrapsResponseDTO.java
  src/main/java/com/gam/api/service/magazine/MagazineServiceImpl.java
Labels: size/M, fix, jjujju

#137 fix: 관리자 메거진 detail count+1 이슈 해결 #136
  src/main/java/com/gam/api/controller/AdminController.java
  src/main/java/com/gam/api/dto/admin/magazine/response/MagazineDetailResponseDTO.java
  src/main/java/com/gam/api/service/admin/AdminService.java
  src/main/java/com/gam/api/service/admin/AdminServiceImpl.java
Labels: size/M, gahee, chore

#139 feat: 탈퇴하기 시큐리티 로직 추가
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/config/SecurityConfig.java
  src/main/java/com/gam/api/config/jwt/CustomAccessDeniedHandler.java
Labels: size/M, size/S, gahee, feat, fix

#144 [CHORE] userTag 리턴값 "" to Null, Token 에러 catch
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/config/jwt/JwtExceptionFilter.java
  src/main/java/com/gam/api/dto/user/response/UserDiscoveryResponseDTO.java
  src/main/java/com/gam/api/dto/user/response/UserMyProfileResponseDTO.java
  src/main/java/com/gam/api/dto/user/response/UserProfileResponseDTO.java
  src/main/java/com/gam/api/dto/user/response/UserResponseDTO.java
  src/main/java/com/gam/api/service/user/UserDetailsServiceImpl.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: bug, size/S, gahee, fix

#142 Feat/#141 delete user
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/repository/AuthProviderRepository.java
  src/main/java/com/gam/api/repository/ReportRepository.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/repository/UserScrapRepository.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/M, gahee, feat

#145 [FEAT🛠️] 유저 권한 조회 api 개발
  src/main/java/com/gam/api/common/message/ResponseMessage.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/dto/user/response/UserStatusResponseDTO.java
  src/main/java/com/gam/api/service/user/UserService.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/M, feat, jjujju
