Repository Gam-develop/gam-server, pull requests merged in 2024-03, with the labels that each got.

#151 [FIX] 매거진 수정 api 변경, @Valid 적용, domain/s3로 폴더링 변경
  src/main/java/com/gam/api/common/ErrorHandler.java
  src/main/java/com/gam/api/domain/admin/controller/AdminController.java
  src/main/java/com/gam/api/domain/admin/dto/magazine/request/MagazineRequestDTO.java
  src/main/java/com/gam/api/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/gam/api/domain/magazine/entity/Magazine.java
  src/main/java/com/gam/api/domain/magazine/entity/Question.java
  src/main/java/com/gam/api/domain/report/dto/request/ReportCreateRequestDTO.java
  src/main/java/com/gam/api/domain/s3/controller/S3Controller.java
  src/main/java/com/gam/api/domain/s3/dto/request/ImageDeleteRequestDTO.java
  src/main/java/com/gam/api/domain/s3/dto/request/PresignedRequestDTO.java
  src/main/java/com/gam/api/domain/s3/dto/response/PresignedResponseDTO.java
  src/main/java/com/gam/api/domain/s3/service/S3Service.java
  src/main/java/com/gam/api/domain/s3/service/S3ServiceImpl.java
  src/main/java/com/gam/api/domain/user/dto/request/UserOnboardRequestDTO.java
  src/main/java/com/gam/api/domain/work/dto/request/WorkEditRequestDTO.java
  src/main/java/com/gam/api/domain/work/service/WorkServiceImpl.java
Labels: size/L, fix

#152 [FIX] userRepository 에서 유저 본인이 작성한 결과물 필터링하는 sql 삭제
  src/main/java/com/gam/api/domain/user/repository/UserRepository.java
Labels: size/XS, fix, jjujju

#154 [fix] 포트폴리오 제목 글자 수 제한 변경
  src/main/java/com/gam/api/domain/work/controller/WorkController.java
  src/main/java/com/gam/api/domain/work/dto/request/WorkCreateRequestDTO.java
Labels: size/S, fix, jjujju

#160 [FEAT🛠️] 탈퇴 계정 재로그인 시 유저 상태 permitted로 변경
  src/main/java/com/gam/api/domain/social/service/SocialCommonServiceImpl.java
Labels: size/XS, feat, jjujju

#158 [FEAT] 봇 ip추적 intetceptor추가
  build.gradle
  src/main/java/com/gam/api/config/WebMvcConfig.java
  src/main/java/com/gam/api/config/bot/PageNotFoundLogInterceptor.java
  src/main/java/com/gam/api/domain/util/controller/UtilController.java
Labels: size/M, gahee, feat

#162 [FIX] 발견-유저 response 수정입니당
  src/main/java/com/gam/api/domain/user/dto/response/UserDiscoveryResponseDTO.java
Labels: size/XS, fix
