Repository Gam-develop/gam-server, pull requests merged in 2024-05, with the labels that each got.

#167 [FIX] 유저 신고 api 수정
  src/main/java/com/gam/api/common/ErrorHandler.java
  src/main/java/com/gam/api/common/exception/ReportException.java
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/domain/report/controller/ReportController.java
  src/main/java/com/gam/api/domain/report/dto/request/ReportCreateRequestDTO.java
  src/main/java/com/gam/api/domain/report/entity/Report.java
  src/main/java/com/gam/api/domain/report/repository/ReportRepository.java
  src/main/java/com/gam/api/domain/report/service/ReportService.java
  src/main/java/com/gam/api/domain/report/service/ReportServiceImpl.java
  src/main/java/com/gam/api/domain/user/entity/User.java
Labels: size/M, gahee, fix

#169 [FIX] 발견-유저 조건 수정
  src/main/java/com/gam/api/domain/user/schedular/UserSchedular.java
  src/main/java/com/gam/api/domain/user/service/UserServiceImpl.java
Labels: size/S, fix

#171 [FIX] 유저 상세보기 api수정
  src/main/java/com/gam/api/domain/user/service/UserServiceImpl.java
  src/main/java/com/gam/api/domain/work/entity/Work.java
Labels: size/XS, gahee, fix

#172 [FIX] 인기유저 api수정
  src/main/java/com/gam/api/domain/user/service/UserServiceImpl.java
Labels: size/S

#177 [FIX] QA 수정사항 반영
  src/main/java/com/gam/api/domain/user/dto/request/UserProfileUpdateRequestDTO.java
  src/main/java/com/gam/api/domain/user/dto/response/SearchUserWorkDTO.java
  src/main/java/com/gam/api/domain/user/dto/response/UserProfileUpdateResponseDTO.java
  src/main/java/com/gam/api/domain/user/service/UserServiceImpl.java
Labels: bug, size/M, chore
