Repository Gam-develop/gam-server, pull requests merged in 2024-06, with the labels that each got.

#179 [FIX] type 받도록 수정, 파일명 제외
  src/main/java/com/gam/api/domain/s3/controller/S3Controller.java
  src/main/java/com/gam/api/domain/s3/dto/request/PresignedRequestDTO.java
  src/main/java/com/gam/api/domain/s3/service/S3Service.java
  src/main/java/com/gam/api/domain/s3/service/S3ServiceImpl.java
Labels: bug, size/M

#181 [FIX] 둘러보기-유저 모든 작품 조회로 수정
  src/main/java/com/gam/api/domain/user/entity/User.java
  src/main/java/com/gam/api/domain/user/service/UserServiceImpl.java
Labels: size/M, fix, jjujju

#175 [FEAT] dev CD 프로세스 변경
  .github/workflows/cd-develop.yml
  appspec.yml
  scripts/deploy.sh
  scripts/switch.sh
Labels: size/M, chore

#184 [FIX] 발견-유저 return 값 롤백
  src/main/java/com/gam/api/domain/user/service/UserServiceImpl.java
Labels: size/M, fix, jjujju

#186 [FIX] 감잡은 디자이너 api수정
  src/main/java/com/gam/api/domain/user/repository/UserRepository.java
  src/main/java/com/gam/api/domain/user/service/UserServiceImpl.java
Labels: size/XS, gahee, feat
