Repository Gam-develop/gam-server, pull requests merged in 2024-01, with the labels that each got.

#107 [REFACTOR🛠] 소셜 로그인 리팩토링
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/dto/kakao/KakaoUserResponse.java
  src/main/java/com/gam/api/service/social/AppleSocialService.java
  src/main/java/com/gam/api/service/social/KakaoSocialService.java
  src/main/java/com/gam/api/service/social/SocialCommonService.java
  src/main/java/com/gam/api/service/social/SocialCommonServiceImpl.java
  src/main/java/com/gam/api/service/social/SocialService.java
Labels: bug, size/L, feat, refactor

#110 fix: 내 포토폴리오 보기 로직 수정
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/S

#112 fix: 온보딩 security 이슈 #111
  src/main/java/com/gam/api/config/SecurityConfig.java
  src/main/java/com/gam/api/config/jwt/CustomAccessDeniedHandler.java
Labels: size/S

#117 [FIX🛠] 검색 - 대소문자 추가
  src/main/java/com/gam/api/repository/MagazineRepository.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/repository/WorkRepository.java
Labels: bug, size/S, gahee, fix

#121 [FIX🛠] user 검색 return null 제거
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
Labels: size/XS

#123 [FIX] 매거진 조회 limit 로직 설정
  src/main/java/com/gam/api/controller/MagazineController.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/service/magazine/MagazineService.java
  src/main/java/com/gam/api/service/magazine/MagazineServiceImpl.java
  src/main/java/com/gam/api/service/social/SocialCommonServiceImpl.java
Labels: size/M, yongtaek, fix

#125 [FIX] Work 생성, 삭제 로직 수정
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/entity/Work.java
  src/main/java/com/gam/api/repository/WorkRepository.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/L, gahee

#128 [FIX] API 리펙토링
  src/main/java/com/gam/api/common/ErrorHandler.java
  src/main/java/com/gam/api/common/exception/ScrapException.java
  src/main/java/com/gam/api/common/message/ExceptionMessage.java
  src/main/java/com/gam/api/controller/AdminController.java
  src/main/java/com/gam/api/controller/BlockController.java
  src/main/java/com/gam/api/controller/MagazineController.java
  src/main/java/com/gam/api/controller/ReportController.java
  src/main/java/com/gam/api/controller/S3Controller.java
  src/main/java/com/gam/api/controller/SocialController.java
  src/main/java/com/gam/api/controller/TestController.java
  src/main/java/com/gam/api/controller/UrlController.java
  src/main/java/com/gam/api/controller/UserController.java
  src/main/java/com/gam/api/controller/WorkController.java
  src/main/java/com/gam/api/dto/user/response/UserScrapsResponseDTO.java
  src/main/java/com/gam/api/dto/work/request/WorkEditRequestDTO.java
  src/main/java/com/gam/api/entity/User.java
  src/main/java/com/gam/api/repository/UserRepository.java
  src/main/java/com/gam/api/repository/UserScrapRepository.java
  src/main/java/com/gam/api/repository/queryDto/userScrap/UserScrapQueryDto.java
  src/main/java/com/gam/api/service/magazine/MagazineService.java
  src/main/java/com/gam/api/service/magazine/MagazineServiceImpl.java
  src/main/java/com/gam/api/service/report/ReportServiceImpl.java
  src/main/java/com/gam/api/service/user/UserServiceImpl.java
  src/main/java/com/gam/api/service/work/WorkServiceImpl.java
Labels: size/L
